apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchase-predict
  labels:
    app: purchase-predict
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-purchase-predict
  template:
    metadata:
      labels:
        app: pod-purchase-predict
    spec:
      containers:
      - name: pod-purchase-predict
        image: us-central1-docker.pkg.dev/project-7c818ee0-8f39-47d7-85d/purchased-docker/purchase_predict_api:latest
        env:
        - name: PORT
          value: "80"
        - name: ENV
          value: "staging"
        - name: MLFLOW_SERVER
          value: "http://10.132.0.2/"
        - name: MLFLOW_REGISTRY_NAME
          value: "purchase_predict"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1G"
            cpu: "500m"